FileVersion = 1

[Project]
Name = "fastlz-beef"
DefaultNamespace = "fastlz"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\fastlzd.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\fastlz.lib"]