FileVersion = 1

[Project]
Name = "fastlz-beef"
DefaultNamespace = "fastlz"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\fastlz_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\fastlz.lib"]